package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat Mar 09 17:49:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat Mar 09 17:49:20 CST 2019
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat Mar 09 17:49:20 CST 2019
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat Mar 09 17:49:20 CST 2019
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat Mar 09 17:49:20 CST 2019
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat Mar 09 17:49:20 CST 2019
     */
    int updateByPrimaryKey(LoanInfo record);
    /**
     *
     * 获取历史平均年化收益率
     * */
    Double selectHistoryAverageRate();

    /**
     * 查询主页信息展示
     * @param paramMap
     * @return
     */
    List<LoanInfo> selectLoanInfoByPage(Map<String, Object> paramMap);

    /**
     * 获取产品的总记录数
     * @param paramMap
     * @return
     */
    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 更新产品剩余可投金额
     * @param paramMap
     * @return
     */
    int updataLeftProductMoneyByLoanId(Map<String, Object> paramMap);

    /**
     * 根据产品类型获取产品所有投资记录
     * @param productStatus
     * @return
     */
    List<LoanInfo> selectLoanInfoByProductStatus(Integer productStatus);
}